# Generated by Django 3.2.8 on 2022-01-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addproductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsnCode', models.IntegerField(max_length=8)),
                ('productname', models.CharField(max_length=20)),
                ('productprice', models.IntegerField()),
            ],
        ),
    ]
